# Generated by Django 4.1.1 on 2022-10-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_person_alter_case_suspects_case_investigator'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
